### ISSUE TITLE
DESeq2 comparisons

### ISSUE THREAD

**Issue by gzentner** [zentnerlab/TSRexploreR#76]
When using `comparison_type = "name"` for DESeq2 differential TSR analysis, the standard format of `condition_glucose_vs_YPD` or similar gives the error `Error: subscript contains invalid names`

**Comment by rpolicastro** [comment]
When using 'names' from DEseq2 you can only specify the contrasts listed in the model after it is run, which in your case would be everything versus 'arrest', since the character vector gets turned into a factor, with the first factor level being 'arrest' due to alphabetical order. If you want more flexibility I recommend using 'contrasts' instead.
